In [2]:
import numpy as np


In [3]:
# creating an array

a= np.array([2,4,5,6,7,1])
a

array([2, 4, 5, 6, 7, 1])

In [4]:
a.ndim

1

In [5]:
# Create two dimensional array with numpy

ar = np.array([[1,2,3],[4,5,6]])

In [6]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
ar.ndim

2

In [11]:
b=np.array([[[1],[4],[5]]])

In [12]:
b

array([[[1],
        [4],
        [5]]])

In [13]:
b.ndim

3

## Zero's and One's

In [14]:
var = np.zeros(10)
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
var1 = np.ones(5)
var1

array([1., 1., 1., 1., 1.])

In [17]:
# create a 3 dimensional array with 4 rows and 5 columns and all elements should be 1

a = np.ones((3,4,5))
a

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [18]:
a.ndim

3

In [25]:
# create a 4 dimensional array with 2 rows and 3 columns and all elements should be 0
arr1 = np.zeros((4,2,3,0))

In [26]:
arr1

array([], shape=(4, 2, 3, 0), dtype=float64)

In [27]:
arr1.ndim

4

### Functions

In [31]:
var = np.array([22,23,24,21,19])
var

array([22, 23, 24, 21, 19])

In [32]:
type(var)

numpy.ndarray

In [33]:
var.argmax() # max value in index position

2

In [34]:
var.argmin()

4

In [35]:
var[2]

24

In [36]:
var[:4]

array([22, 23, 24, 21])

In [37]:
var

array([22, 23, 24, 21, 19])

In [38]:
var[2:-1]

array([24, 21])

In [39]:
var.dtype

dtype('int64')

In [42]:
var2 = np.array([22,23.1,24,21,19])
var2

array([22. , 23.1, 24. , 21. , 19. ])

In [41]:
var2.dtype

dtype('float64')

In [43]:
var.size

5

In [ ]:
# create a numpy array with size 5 and datatype of floating point

In [44]:
var2 = np.array([22,23.1,24,21,19])
var2

array([22. , 23.1, 24. , 21. , 19. ])

In [ ]:
# create a two dimensional array
# four arrays in the external array
# it should have two elements in each

In [45]:
array_2d = np.array([[1,2],[3,4],[5,6],[7,8]])
array_2d

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Resize and Reshape

In [46]:
q = np.arange(15)
q

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
q.ndim

1

In [48]:
w = np.arange(15).reshape(3,5)

In [49]:
w

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
w.max()

14

In [51]:
w.min()

0

In [52]:
np.sqrt(w)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [53]:
np.log(w)

<ipython-input-53-993f9552f820>:1: RuntimeWarning: divide by zero encountered in log
  np.log(w)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733]])

In [54]:
np.exp(w)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06]])

### Transpose

In [55]:
w

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
t = w.T

In [57]:
t

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [58]:
t.shape

(5, 3)

### Floor and Ceil

In [59]:
arr3 = np.array([10.8,3.38,6.12,5.3])
arr3

array([10.8 ,  3.38,  6.12,  5.3 ])

In [60]:
np.floor(arr3)

array([10.,  3.,  6.,  5.])

In [61]:
np.ceil(arr3)

array([11.,  4.,  7.,  6.])

In [62]:
np.round(arr3)

array([11.,  3.,  6.,  5.])

### Stacking

In [63]:
arr23 = np.arange(10).reshape(2,5)
arr23

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
arr24 = np.arange(20).reshape(4,5)
arr24

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
np.vstack((arr23,arr24))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [67]:
np.hstack((arr23,arr24))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

In [68]:
arr25 = np.arange(20).reshape(5,4)
arr25


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [69]:
arr26 = np.arange(10).reshape(5,2)
arr26

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [70]:
np.hstack((arr25,arr26))

array([[ 0,  1,  2,  3,  0,  1],
       [ 4,  5,  6,  7,  2,  3],
       [ 8,  9, 10, 11,  4,  5],
       [12, 13, 14, 15,  6,  7],
       [16, 17, 18, 19,  8,  9]])

In [ ]:
# for vstack the number of columns of two arrys should be same, and for horizondal stack number of rows should be same.

### NUmpy Split

In [71]:
arr27 = np.arange(100).reshape(10,10)
arr27

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
np.vsplit(arr27,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [73]:
np.hsplit(arr27,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [74]:
# create a numpy array with shape of 200, array should be contains 20 rows and 10 columns,
# split the array to vertically and horizondally


arr28 = np.arange(200).reshape(20,10)
arr28

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [75]:
np.vsplit(arr28,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]),
 array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
        [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
        [180, 181,